spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}


server:
  port: 8080

logging:
  level:
    root: INFO

