spring:
  application:
    name: customers
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    info:
      enabled: true
  info:
    defaults:
      enabled: true

info:
  app:
    name: customers-service
    description: Customers microservice
    version: 1.0.0

logging:
  level:
    com.ordersystem.customers: INFO